Repository team-dododok/honeypot-be, pull requests merged in 2024-12, with the labels that each got.

#61 DD-140 refactor : accessToken 재발급 로직에서 만료 시간검증하지 않도록 수정
  src/main/java/com/dodok/honeypot/domain/auth/error/AuthErrorCode.java
  src/main/java/com/dodok/honeypot/domain/auth/service/KakaoSocialLoginService.java
  src/main/java/com/dodok/honeypot/global/auth/JwtUtil.java
Labels: 민정

#63 DD-144 그룹 내 보낸 칭찬 조회, 받은 칭찬 조회에 랜덤 프로필 이미지 url 반영
  src/main/java/com/dodok/honeypot/domain/receivepraise/dto/res/GetGroupReceivePraiseResDto.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/dto/res/ReceivePraiseInfoResDto.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/mapper/ReceivePraiseMapper.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/service/GetGroupReceivePraiseService.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/dto/res/GetGroupSendPraiseResDto.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/dto/res/SendPraiseInfoResDto.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/mapper/SendPraiseMapper.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/service/GetGroupSendPraiseService.java
Labels: 진영

#62 DD-143 그룹 조회 시 받은 칭찬 보낸 칭찬 개수 바뀌던 문제 수정
  src/main/java/com/dodok/honeypot/domain/group/repository/GroupInfosQueryRepositoryImpl.java
Labels: 진영

#65 DD 76 로그아웃 API
  src/main/java/com/dodok/honeypot/application/auth/controller/AuthController.java
  src/main/java/com/dodok/honeypot/domain/auth/dto/req/KakaoServerLogOutReqDto.java
  src/main/java/com/dodok/honeypot/domain/auth/dto/res/KakaoLogOutResDto.java
  src/main/java/com/dodok/honeypot/domain/auth/helper/KakaoSocialHelper.java
  src/main/java/com/dodok/honeypot/domain/auth/kakao/KakaoFeignClient.java
  src/main/java/com/dodok/honeypot/domain/auth/repository/KakaoSocialRepository.java
  src/main/java/com/dodok/honeypot/domain/auth/service/KakaoSocialLogoutService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: 민정

#67 DD-147 refactor : 그룹 삭제(soft delete)를 위한 작업 및 api 수정 사항
  src/main/java/com/dodok/honeypot/domain/group/entity/Group.java
  src/main/java/com/dodok/honeypot/domain/group/helper/GroupHelper.java
  src/main/java/com/dodok/honeypot/domain/group/repository/GroupInfosQueryRepository.java
  src/main/java/com/dodok/honeypot/domain/group/repository/GroupInfosQueryRepositoryImpl.java
  src/main/java/com/dodok/honeypot/domain/group/repository/GroupNameAndMembersQueryRepository.java
  src/main/java/com/dodok/honeypot/domain/group/repository/GroupNameAndMembersQueryRepositoryImpl.java
  src/main/java/com/dodok/honeypot/domain/group/repository/GroupNameAndTotalCountQueryRepository.java
  src/main/java/com/dodok/honeypot/domain/group/repository/GroupNameAndTotalCountQueryRepositoryImpl.java
  src/main/java/com/dodok/honeypot/domain/group/repository/GroupNameSearchQueryRepository.java
  src/main/java/com/dodok/honeypot/domain/group/repository/GroupNameSearchQueryRepositoryImpl.java
  src/main/java/com/dodok/honeypot/domain/group/repository/GroupRepository.java
  src/main/java/com/dodok/honeypot/domain/group/service/UpdateGroupOrderService.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/entity/SendPraise.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/helper/SendPraiseHelper.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/repository/SendPraiseRepository.java
Labels: 진우

#70 DD-157 feat : 콜백 api 헤더와 필수 파라미터 추가
  src/main/java/com/dodok/honeypot/application/sendpraise/controller/SendPraiseController.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/dto/req/CheckSendPraiseSentReqDto.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/service/CheckSendPraiseSentService.java
Labels: 진우

#71 DD-157 feat: SendStatus에 단톡/갠톡/혼톡 추가 및 변경에 따른 조회 로직 수정
  src/main/java/com/dodok/honeypot/application/sendpraise/controller/SendPraiseController.java
  src/main/java/com/dodok/honeypot/domain/badge/helper/CheckSendPraiseBadgeHelper.java
  src/main/java/com/dodok/honeypot/domain/praise/helper/PraiseHelper.java
  src/main/java/com/dodok/honeypot/domain/praise/repository/MemberPraiseInfoQueryRepository.java
  src/main/java/com/dodok/honeypot/domain/praise/repository/MemberPraiseInfoQueryRepositoryImpl.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/dto/res/GetReceivedPraiseResDto.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/mapper/ReceivePraiseMapper.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/service/GetReceivedPraiseService.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/service/SaveReceivePraiseService.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/entity/SendPraise.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/entity/SendStatus.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/helper/SendPraiseHelper.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/repository/GroupSendPraiseGetInfoQueryRepository.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/repository/GroupSendPraiseGetInfoQueryRepositoryImpl.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/repository/SendPraiseRepository.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/service/CheckSendPraiseSentService.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/service/CreateSendPraiseService.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/service/GetSendPraiseSentService.java
Labels: 진우

#76 DD-96 fix : 그룹별 꿀도장 조회로직 수정
  src/main/java/com/dodok/honeypot/application/stamp/controller/StampController.java
  src/main/java/com/dodok/honeypot/domain/stamp/helper/StampByGroupHelper.java
  src/main/java/com/dodok/honeypot/domain/stamp/mapper/StampByGroupMapper.java
  src/main/java/com/dodok/honeypot/domain/stamp/repository/ReceivedStampByMemberQueryRepository.java
  src/main/java/com/dodok/honeypot/domain/stamp/repository/ReceivedStampByMemberQueryRepositoryImpl.java
  src/main/java/com/dodok/honeypot/domain/stamp/repository/StampRepository.java
  src/main/java/com/dodok/honeypot/domain/stamp/service/GetReceivedStampByGroupService.java
  src/main/java/com/dodok/honeypot/domain/stamp/service/GetSentStampByGroupService.java
Labels: 진우

#78 DD-164 받은 칭찬 조회 시 도장 이름까지 보이도록 추가
  src/main/java/com/dodok/honeypot/domain/receivepraise/dto/res/GetReceivedPraiseResDto.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/mapper/ReceivePraiseMapper.java
Labels: 진영

#79 DD-164 fix : 보낸 칭찬이 없을 때도 검색 잘되도록 쿼리 수정
  src/main/java/com/dodok/honeypot/domain/praise/repository/MemberPraiseInfoQueryRepositoryImpl.java
Labels: 진영
