Repository team-dododok/honeypot-be, pull requests merged in 2024-11, with the labels that each got.

#19 DD-73 feat : 전체 꿀도장 조회 api 생성
  src/main/java/com/dodok/honeypot/application/stamp/controller/StampController.java
  src/main/java/com/dodok/honeypot/domain/stamp/dto/res/AllStampResDto.java
  src/main/java/com/dodok/honeypot/domain/stamp/dto/res/StampDto.java
  src/main/java/com/dodok/honeypot/domain/stamp/helper/HoneyStampHelper.java
  src/main/java/com/dodok/honeypot/domain/stamp/helper/StampHelper.java
  src/main/java/com/dodok/honeypot/domain/stamp/mapper/StampMapper.java
  src/main/java/com/dodok/honeypot/domain/stamp/repository/StampRepository.java
  src/main/java/com/dodok/honeypot/domain/stamp/service/StampService.java
  src/main/java/com/dodok/honeypot/global/config/security/SecurityConfig.java
Labels: 진우

#23 DD-53 그룹 순서 변경 API
  src/main/java/com/dodok/honeypot/application/group/controller/GroupController.java
  src/main/java/com/dodok/honeypot/domain/group/dto/req/GroupOrderReqDto.java
  src/main/java/com/dodok/honeypot/domain/group/dto/req/GroupOrderUpdateReqDto.java
  src/main/java/com/dodok/honeypot/domain/group/entity/Group.java
  src/main/java/com/dodok/honeypot/domain/group/error/GroupErrorCode.java
  src/main/java/com/dodok/honeypot/domain/group/service/UpdateGroupOrderService.java
  src/main/java/com/dodok/honeypot/global/config/security/SecurityConfig.java
Labels: 진영

#25 DD 79 feat : 보낸칭찬의 uuid를 통해 칭찬을 저장하는 api
  src/main/java/com/dodok/honeypot/application/receivepraise/controller/ReceivePraiseController.java
  src/main/java/com/dodok/honeypot/application/sendpraise/controller/SendPraiseController.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/dto/req/SaveReceivePraiseReqDto.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/entity/ReceivePraise.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/helper/ReceivePraiseHelper.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/SaveReceivePraiseService.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/error/SendPraiseErrorCode.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/helper/SendPraiseHelper.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/repository/SendPraiseRepository.java
  src/main/java/com/dodok/honeypot/global/config/security/SecurityConfig.java
Labels: 진우

#18 Dd 44 카카오 로그인 API
  build.gradle
  src/main/java/com/dodok/honeypot/HoneypotApplication.java
  src/main/java/com/dodok/honeypot/application/auth/controller/AuthController.java
  src/main/java/com/dodok/honeypot/domain/auth/dto/JwtToken.java
  src/main/java/com/dodok/honeypot/domain/auth/dto/req/KakaoLoginReqDto.java
  src/main/java/com/dodok/honeypot/domain/auth/dto/res/KakaoLoginResDto.java
  src/main/java/com/dodok/honeypot/domain/auth/dto/res/UserInfoFromKakaoResDto.java
  src/main/java/com/dodok/honeypot/domain/auth/entity/KakaoSocial.java
  src/main/java/com/dodok/honeypot/domain/auth/error/AuthErrorCode.java
  src/main/java/com/dodok/honeypot/domain/auth/helper/KakaoSocialHelper.java
  src/main/java/com/dodok/honeypot/domain/auth/kakao/KakaoFeignClient.java
  src/main/java/com/dodok/honeypot/domain/auth/mapper/KakaoSocialMapper.java
  src/main/java/com/dodok/honeypot/domain/auth/repository/KakaoSocialRepository.java
  src/main/java/com/dodok/honeypot/domain/auth/service/KakaoSocialLoginService.java
  src/main/java/com/dodok/honeypot/domain/auth/type/MemberRole.java
  src/main/java/com/dodok/honeypot/domain/member/entity/Member.java
  src/main/java/com/dodok/honeypot/domain/member/entity/ServiceConsent.java
  src/main/java/com/dodok/honeypot/domain/member/helper/MemberHelper.java
  src/main/java/com/dodok/honeypot/domain/member/helper/ServiceConsentHelper.java
  src/main/java/com/dodok/honeypot/global/auth/JwtUtil.java
  src/main/java/com/dodok/honeypot/global/config/security/SecurityConfig.java
  src/main/java/com/dodok/honeypot/global/reids/entity/RefreshToken.java
  src/main/java/com/dodok/honeypot/global/reids/helper/RefreshTokenHelper.java
  src/main/java/com/dodok/honeypot/global/reids/repository/RefreshTokenRepository.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: 민정

#28 DD-88 feat : 받은칭찬을 삭제하는 api
  src/main/java/com/dodok/honeypot/application/receivepraise/controller/ReceivePraiseController.java
  src/main/java/com/dodok/honeypot/application/stamp/controller/StampController.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/error/ReceivedPraiseErrorCode.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/helper/ReceivePraiseHelper.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/service/DeleteReceivedPraiseService.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/service/SaveReceivePraiseService.java
Labels: 진우

#30 DD-105 feat : jwt토큰에서 memberId를 뽑아오는메서드
  src/main/java/com/dodok/honeypot/application/receivepraise/controller/ReceivePraiseController.java
  src/main/java/com/dodok/honeypot/domain/auth/service/KakaoSocialLoginService.java
  src/main/java/com/dodok/honeypot/global/auth/JwtUtil.java
  src/main/java/com/dodok/honeypot/global/auth/MemberId.java
  src/main/java/com/dodok/honeypot/global/auth/MemberIdArgumentResolver.java
  src/main/java/com/dodok/honeypot/global/config/security/CorsConfig.java
  src/main/java/com/dodok/honeypot/global/controller/HealthCheckController.java
  src/main/java/com/dodok/honeypot/global/redis/entity/RefreshToken.java
  src/main/java/com/dodok/honeypot/global/redis/helper/RefreshTokenHelper.java
  src/main/java/com/dodok/honeypot/global/redis/repository/RefreshTokenRepository.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: 진우

#27 DD-85 그룹 별 받은 칭찬 보기 API 구현 (페이지네이션)
  src/main/java/com/dodok/honeypot/application/receivepraise/controller/ReceivePraiseController.java
  src/main/java/com/dodok/honeypot/domain/group/helper/GroupHelper.java
  src/main/java/com/dodok/honeypot/domain/group/repository/GroupRepository.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/dto/ReceivePraiseInfo.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/dto/res/GetGroupReceivePraiseResDto.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/helper/ReceivePraiseHelper.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/mapper/ReceivePraiseMapper.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/repository/GroupReceivePraiseGetInfoQueryRepository.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/repository/GroupReceivePraiseGetInfoQueryRepositoryImpl.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/repository/ReceivePraiseRepository.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/service/GetGroupReceivePraiseService.java
  src/main/java/com/dodok/honeypot/global/config/security/SecurityConfig.java
  src/main/java/com/dodok/honeypot/global/dto/SliceInfo.java
Labels: 진영

#31 DD - 72 AccessToken 재발급 API 구현
  src/main/java/com/dodok/honeypot/application/auth/controller/AuthController.java
  src/main/java/com/dodok/honeypot/domain/auth/dto/req/ReissueJwtTokenReqDto.java
  src/main/java/com/dodok/honeypot/domain/auth/dto/res/ReissueJwtTokenResDto.java
  src/main/java/com/dodok/honeypot/domain/auth/error/AuthErrorCode.java
  src/main/java/com/dodok/honeypot/domain/auth/service/KakaoSocialLoginService.java
  src/main/java/com/dodok/honeypot/global/auth/JwtUtil.java
  src/main/java/com/dodok/honeypot/global/redis/entity/RefreshToken.java
  src/main/java/com/dodok/honeypot/global/redis/helper/RefreshTokenHelper.java
Labels: 민정

#34 Dd 72-1
  src/main/java/com/dodok/honeypot/global/auth/JwtUtil.java
Labels: 민정

#29 DD-106 내 그룹 정보에 주고받은 칭찬 수 함께 응답
  src/main/java/com/dodok/honeypot/application/sendpraise/controller/SendPraiseController.java
  src/main/java/com/dodok/honeypot/domain/group/dto/GroupPraiseCountInfo.java
  src/main/java/com/dodok/honeypot/domain/group/dto/GroupWithMembersInfo.java
  src/main/java/com/dodok/honeypot/domain/group/repository/GroupInfosQueryRepositoryImpl.java
  src/main/java/com/dodok/honeypot/domain/member/dto/res/MemberInfoResDto.java
  src/main/java/com/dodok/honeypot/domain/member/mapper/MemberMapper.java
  src/main/java/com/dodok/honeypot/domain/member/service/GetMemberInfoService.java
  src/main/java/com/dodok/honeypot/domain/praise/dto/info/MemberPraiseInfo.java
  src/main/java/com/dodok/honeypot/domain/praise/helper/PraiseHelper.java
  src/main/java/com/dodok/honeypot/domain/praise/repository/MemberPraiseInfoQueryRepository.java
  src/main/java/com/dodok/honeypot/domain/praise/repository/MemberPraiseInfoQueryRepositoryImpl.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/dto/ReceivePraiseInfo.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/repository/ReceivePraiseRepository.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/dto/SendPraiseInfo.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/dto/res/GetGroupSendPraiseResDto.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/helper/SendPraiseHelper.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/mapper/SendPraiseMapper.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/repository/GroupSendPraiseGetInfoQueryRepository.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/repository/GroupSendPraiseGetInfoQueryRepositoryImpl.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/repository/SendPraiseRepository.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/service/GetGroupSendPraiseService.java
  src/main/java/com/dodok/honeypot/global/config/security/SecurityConfig.java
Labels: 진영

#35 DD-97 feat : 칭찬을 보냈을 때 보낸칭찬 정보를 조회하는 api
  src/main/java/com/dodok/honeypot/application/receivepraise/controller/ReceivePraiseController.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/dto/res/GetReceivedPraiseResDto.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/helper/ReceivePraiseHelper.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/mapper/ReceivePraiseMapper.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/repository/ReceivePraiseRepository.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/service/GetReceivedPraiseService.java
  src/main/java/com/dodok/honeypot/global/auth/JwtUtil.java
Labels: 진우

#37 DD-113 refactor: 컨트롤러 memberId 모두 header통해 받도록 수정
  src/main/java/com/dodok/honeypot/application/badge/controller/BadgeController.java
  src/main/java/com/dodok/honeypot/application/group/controller/GroupController.java
  src/main/java/com/dodok/honeypot/application/member/controller/MemberController.java
  src/main/java/com/dodok/honeypot/application/receivepraise/controller/ReceivePraiseController.java
  src/main/java/com/dodok/honeypot/application/sendpraise/controller/SendPraiseController.java
  src/main/java/com/dodok/honeypot/application/stamp/controller/StampController.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/dto/req/SaveReceivePraiseReqDto.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/error/ReceivedPraiseErrorCode.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/helper/ReceivePraiseHelper.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/repository/ReceivePraiseRepository.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/service/DeleteReceivedPraiseService.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/service/SaveReceivePraiseService.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/dto/req/SendPraiseReqDto.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/service/CreateSendPraiseService.java
  src/main/java/com/dodok/honeypot/domain/stamp/service/GetReceivedStampByGroupService.java
  src/main/java/com/dodok/honeypot/domain/stamp/service/GetSentStampByGroupService.java
  src/main/java/com/dodok/honeypot/global/config/security/SecurityConfig.java
Labels: 진영

#38 DD-110 그룹명으로 검색 API
  src/main/java/com/dodok/honeypot/application/group/controller/GroupController.java
  src/main/java/com/dodok/honeypot/domain/group/dto/SearchGroupInfo.java
  src/main/java/com/dodok/honeypot/domain/group/dto/res/GetSearchGroupNameResDto.java
  src/main/java/com/dodok/honeypot/domain/group/helper/GroupHelper.java
  src/main/java/com/dodok/honeypot/domain/group/mapper/GroupMapper.java
  src/main/java/com/dodok/honeypot/domain/group/repository/GroupNameSearchQueryRepository.java
  src/main/java/com/dodok/honeypot/domain/group/repository/GroupNameSearchQueryRepositoryImpl.java
  src/main/java/com/dodok/honeypot/domain/group/repository/GroupRepository.java
  src/main/java/com/dodok/honeypot/domain/group/service/GetSearchGroupNameService.java
Labels: 진영

#40 DD-120 feat : 전체 꿀도장 조회 dto에 id추가
  src/main/java/com/dodok/honeypot/domain/stamp/dto/res/StampDto.java
Labels: 진우

#41 DD-110 그룹명 검색 시 동일한 그룹명 상단에 위치되도록 수정
  src/main/java/com/dodok/honeypot/domain/group/repository/GroupNameSearchQueryRepositoryImpl.java
Labels: 진영

#42 DD-122 refactor : 로그인 ResponseDto에 사용자 이름 추가
  src/main/java/com/dodok/honeypot/domain/auth/dto/res/KakaoLoginResDto.java
  src/main/java/com/dodok/honeypot/domain/auth/service/KakaoSocialLoginService.java
Labels: 민정

#44 DD-128 fix : 칭찬을 저장할때 groupId를 바디로 받도록 변경
  src/main/java/com/dodok/honeypot/domain/receivepraise/dto/req/SaveReceivePraiseReqDto.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/service/SaveReceivePraiseService.java
Labels: 진우

#43 DD-54 feat : 이메일 인증 로직 추가
  build.gradle
  src/main/java/com/dodok/honeypot/HoneypotApplication.java
  src/main/java/com/dodok/honeypot/application/auth/controller/AuthController.java
  src/main/java/com/dodok/honeypot/domain/auth/dto/req/SendMailReqDto.java
  src/main/java/com/dodok/honeypot/domain/auth/error/AuthErrorCode.java
  src/main/java/com/dodok/honeypot/domain/auth/service/CheckMailService.java
  src/main/java/com/dodok/honeypot/domain/auth/service/SendMailService.java
  src/main/java/com/dodok/honeypot/global/config/AsyncConfig.java
  src/main/java/com/dodok/honeypot/global/config/security/SecurityConfig.java
  src/main/java/com/dodok/honeypot/global/redis/entity/MailVerification.java
  src/main/java/com/dodok/honeypot/global/redis/helper/MailVerificationHelper.java
  src/main/java/com/dodok/honeypot/global/redis/repository/MailVerificationRepository.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/templates/send-mail.html
Labels: 진우

#39 DD-109 JwtFIlter, Security 설정
  build.gradle
  src/main/java/com/dodok/honeypot/application/member/controller/MemberController.java
  src/main/java/com/dodok/honeypot/domain/auth/error/AuthErrorCode.java
  src/main/java/com/dodok/honeypot/global/auth/JwtAccessDeniedHandler.java
  src/main/java/com/dodok/honeypot/global/auth/JwtAuthenticationEntryPoint.java
  src/main/java/com/dodok/honeypot/global/auth/JwtExceptionFilter.java
  src/main/java/com/dodok/honeypot/global/auth/JwtFilter.java
  src/main/java/com/dodok/honeypot/global/auth/JwtUtil.java
  src/main/java/com/dodok/honeypot/global/config/security/SecurityConfig.java
Labels: 민정

#49 DD-130 그룹 id로 그룹 이름 및 칭찬 개수 조회 API 및 CORS 추가
  src/main/java/com/dodok/honeypot/application/group/controller/GroupController.java
  src/main/java/com/dodok/honeypot/domain/group/dto/GroupNamePraiseCountInfo.java
  src/main/java/com/dodok/honeypot/domain/group/dto/res/GetGroupNameAndPraiseCountResDto.java
  src/main/java/com/dodok/honeypot/domain/group/helper/GroupHelper.java
  src/main/java/com/dodok/honeypot/domain/group/mapper/GroupMapper.java
  src/main/java/com/dodok/honeypot/domain/group/repository/GroupNameAndTotalCountQueryRepository.java
  src/main/java/com/dodok/honeypot/domain/group/repository/GroupNameAndTotalCountQueryRepositoryImpl.java
  src/main/java/com/dodok/honeypot/domain/group/repository/GroupRepository.java
  src/main/java/com/dodok/honeypot/domain/group/service/GetGroupNameAndTotalPraiseCountService.java
  src/main/java/com/dodok/honeypot/global/config/security/CorsConfig.java
Labels: 진영

#50 DD-132 프로필 이미지 수정 API 변경
  src/main/java/com/dodok/honeypot/domain/member/dto/req/MemberUpdateReqDto.java
  src/main/java/com/dodok/honeypot/domain/member/entity/Member.java
  src/main/java/com/dodok/honeypot/domain/member/service/UpdateMemberInfoService.java
Labels: 진영

#51 DD-134 특정 그룹이 받은 꿀도장의 정보 조회 시 stampId 빠져있던 오류 수정
  src/main/java/com/dodok/honeypot/domain/stamp/repository/ReceivedStampByGroupQueryRepositoryImpl.java
Labels: 진영

#54 DD-135 멤버 이용약관 조회 및 수정 API
  src/main/java/com/dodok/honeypot/application/member/controller/MemberController.java
  src/main/java/com/dodok/honeypot/domain/member/dto/req/MemberServiceConsentUpdateReqDto.java
  src/main/java/com/dodok/honeypot/domain/member/dto/res/GetMemberConsentResDto.java
  src/main/java/com/dodok/honeypot/domain/member/entity/ServiceConsent.java
  src/main/java/com/dodok/honeypot/domain/member/error/ServiceConsentErrorCode.java
  src/main/java/com/dodok/honeypot/domain/member/helper/ServiceConsentHelper.java
  src/main/java/com/dodok/honeypot/domain/member/mapper/ServiceConsentMapper.java
  src/main/java/com/dodok/honeypot/domain/member/repository/ServiceConsentRepository.java
  src/main/java/com/dodok/honeypot/domain/member/service/GetMemberConsentService.java
  src/main/java/com/dodok/honeypot/domain/member/service/UpdateMemberServiceConsentService.java
Labels: 진영

#47 DD-129 refactor : 칭찬보내기 dto에 title을 없애기
  src/main/java/com/dodok/honeypot/domain/sendpraise/dto/req/SendPraiseReqDto.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/entity/SendPraise.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/helper/SendPraiseHelper.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/service/CreateSendPraiseService.java
Labels: 진우

#46 DD-126 feat : 카카오톡 공유하기 성공시 콜백 api와 폴링 api 컨트롤러 부분 만 구현
  src/main/java/com/dodok/honeypot/application/auth/controller/AuthController.java
  src/main/java/com/dodok/honeypot/application/receivepraise/controller/ReceivePraiseController.java
  src/main/java/com/dodok/honeypot/application/sendpraise/controller/SendPraiseController.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/dto/req/checkSendPraiseSentReqDto.java
  src/main/java/com/dodok/honeypot/global/auth/JwtFilter.java
  src/main/java/com/dodok/honeypot/global/config/security/SecurityConfig.java
Labels: 진우

#55 DD 82 : 보낸 꿀 / 받은 꿀 그룹 수정 API
  src/main/java/com/dodok/honeypot/application/group/controller/GroupController.java
  src/main/java/com/dodok/honeypot/domain/group/dto/req/GroupChangeReqDto.java
  src/main/java/com/dodok/honeypot/domain/group/service/ChangeGroupService.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/entity/ReceivePraise.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/helper/ReceivePraiseHelper.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/entity/SendPraise.java
  src/main/java/com/dodok/honeypot/domain/sendpraise/helper/SendPraiseHelper.java
Labels: 민정

#57 프론트 엑세스토큰 만료 test 위해서 엑세스토큰 만료 시간 변경
  src/main/java/com/dodok/honeypot/global/auth/JwtUtil.java
Labels: 민정

#56 DD-136 feat : 받은 칭찬을 여러개 삭제할 수 있도록 함
  src/main/java/com/dodok/honeypot/application/receivepraise/controller/ReceivePraiseController.java
  src/main/java/com/dodok/honeypot/domain/receivepraise/service/DeleteReceivedPraiseService.java
Labels: 진우

#60 DD-139 feat : 그룹 생성시 그룹id 응답으로 내려줌
  src/main/java/com/dodok/honeypot/application/group/controller/GroupController.java
  src/main/java/com/dodok/honeypot/domain/group/dto/res/CreateGroupResDto.java
  src/main/java/com/dodok/honeypot/domain/group/helper/GroupHelper.java
  src/main/java/com/dodok/honeypot/domain/group/mapper/GroupMapper.java
  src/main/java/com/dodok/honeypot/domain/group/service/CreateGroupService.java
Labels: 진우
